### ISSUE TITLE
Global search error

### ISSUE THREAD

**Issue by idimkk** [IvanJosipovic/BlazorTable#135]
Hi!
Thanks for fantastic library!

I have a strange error:
If I use ShowSearchBar="true" and Columns with Template this causes an error.

Sample
```
<Table TableItem="Object" Items="data" ShowSearchBar="true" TableClass="table" TableRowClass="@(x => x.GetRowClass())">
  <Column TableItem="Object" Title="Id" Field="@(x => x.ShortId)" Sortable="false" Filterable="true" />
    <Column TableItem="Object" Title="Request" Sortable="false" Filterable="false">
      <Template>
        <button @onclick="@(r => GetLog(@context))" class="btn btn-light">RQ</button>
      </Template>
    </Column>
</Table>
```

Next, we need to refresh the page, because it stops working.

Thank you!

**Comment by IvanJosipovic** [comment]
Thank you for reporting this Bug, it has been fixed in 1.11.1

**Comment by idimkk** [comment]
Hi @IvanJosipovic

Thanks for your update!
I updated nuget, but error still exists.

**Comment by IvanJosipovic** [comment]
Hi @idimkk, It's likely something more specific in your scenario.

Could you please look at [135.razor](https://github.com/IvanJosipovic/BlazorTable/blob/master/src/BlazorTable.Sample.Shared/Bugs/135.razor) and update the repro scenario so that it fails?

Thank you

**Comment by idimkk** [comment]
Sorry, I recreate the file Razor and everything works well.
It's strange, but now it works fine.
Many thanks!

**Comment by tkennedy13** [comment]
I'm using version 1.11.1 and I get  an error when I have a template column that uses shows a field from a related model. The error is `System.NullReferenceException: 'Object reference not set to an instance of an object.'` 

Here is what the offending column look like:

```
<Column TableItem="Model" Title="Region" Field="@(x => x.Region.Name)" Sortable="true" Filterable="true" Width="5%">
                    <Template>
                        @(context.Region != null ? context.Region.Name : string.Empty)
                    </Template>
```

Here is my entire table:

            ```
<Table TableItem="Model" Items="_churches" PageSize="50" ColumnReorder="true" ShowSearchBar="true" RowClickAction="RowClick" SelectionType="SelectionType.Single"
                   TableClass="table table-hover table-sm" TableHeadClass="thead-light">
                <Column TableItem="Model" Title="Name" Field="@(x => x.Name)" Sortable="true" Filterable="true" DefaultSortColumn="true" Width="10%" />
                <Column TableItem="Model" Title="Phone Number" Field="@(x => x.PhoneNumber)" Sortable="true" Filterable="false" Width="5%" />
                <Column TableItem="Model" Title="Email" Field="@(x => x.EmailAddress)" Sortable="true" Filterable="false" Width="10%">
                    <Template>
                        <a href="mailto:@context.EmailAddress">@context.EmailAddress</a>
                    </Template>
                </Column> 
                <Column TableItem="Model" Title="Locality" Field="@(x => x.Locality)" Sortable="true" Filterable="true" Width="5%" />
               <Column TableItem="Model" Title="Region" Field="@(x => x.Region.Name)" Sortable="true" Filterable="true" Width="5%">
                    <Template>
                        @(context.Region != null ? context.Region.Name : string.Empty)
                    </Template>
                </Column>                
                <LoadingDataTemplate>
                    <div class="text-center">
                        <p><em>Loading...</em></p>
                    </div>
                </LoadingDataTemplate>
                <Pager ShowPageNumber="true" ShowTotalCount="true" />
            </Table>
```
